export const INIT_APP = "INIT_APP";

export const SCROLLING_TRUE = "SCROLLING_TRUE";

export const GET_SEARCH_RESULTS = "GET_SEARCH_RESULTS";

export const UPDATE_TRENDING_RESULTS = "UPDATE_TRENDING_RESULTS";
