export const INIT_APP = "INIT_APP";

export const TRENDING_SCROLLING_TRUE = "TRENDING_SCROLLING_TRUE";

export const SEARCH_SCROLLING_TRUE = "SEARCH_SCROLLING_TRUE";

export const SWITCH_TO_SEARCH_MODE = "SWITCH_TO_SEARCH_MODE";

export const SWITCH_TO_TRENDING_MODE = "SWITCH_TO_TRENDING_MODE";

export const GET_SEARCH_RESULTS = "GET_SEARCH_RESULTS";

export const UPDATE_TRENDING_RESULTS = "UPDATE_TRENDING_RESULTS";

export const UPDATE_SEARCH_RESULTS = "UPDATE_SEARCH_RESULTS";

export const INIT_ASC_SORT = "INIT_ASC_SORT";
